title: Moina Vernon
#logo: assets/img/headshot_circle.png
description: Highly motivated and results-oriented computer science professional with a Master's degree and experience in software development, database management, and cybersecurity.  Proven ability to design, develop, and deploy full-stack web applications, manage backend integrations, and provide detailed feedback and support to peers.  Passionate about leveraging technology to solve complex problems and enhance user experiences.

#show_downloads: true
theme: jekyll-theme-minimal
